modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="fistful_o_ores"
version="1.0.0"
displayName="Fistful o' Ores"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tomat, MCreator"

[[dependencies.fistful_o_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




